name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      JAVA_HOME: /opt/graalvm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache GraalVM and nativeimage
      id: graalvm-cache
      uses: actions/cache@v1
      with:
        path: /opt/graalvm
        key: graalvm-20.0.0-ee
    - name: Set up GraalVM and nativeimage
      if: steps.graalvm-cache.outputs.cache-hit != 'true'
      env:
        GRAALVM_PKG: "https://web.archive.org/web/20200228064159/https%3A%2F%2Fdownload.oracle.com%2Fotn%2Futilities_drivers%2Foracle-labs%2Fgraalvm-ee-java11-linux-amd64-20.0.0.tar.gz%3FAuthParam%3D1582872216_1c709e264459fe8f38146174374aa6b8"
        NATIVEIMAGE_PKG: "https://web.archive.org/web/20200228083230/https%3A%2F%2Fdownload.oracle.com%2Fotn%2Futilities_drivers%2Foracle-labs%2Fnative-image-installable-svm-svmee-java11-linux-amd64-20.0.0.jar%3FAuthParam%3D1582878853_656f39126124eddc70c07568cddaf024"
      run: |
        export PATH="$PATH:$JAVA_HOME/bin"
        mkdir -p "${JAVA_HOME}" && curl -L "${GRAALVM_PKG}" | tar --strip-components=1 -xzvC "${JAVA_HOME}"
        curl -Lo /tmp/nativeimage.jar "${NATIVEIMAGE_PKG}" && sudo -E gu install /tmp/nativeimage.jar && rm /tmp/nativeimage.jar
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - name: Set up swap
      run: |
        sudo fallocate -l 8G /ADDTIONAL_SWAP_FILE
        sudo chmod 600 /ADDTIONAL_SWAP_FILE
        sudo mkswap /ADDTIONAL_SWAP_FILE
        sudo swapon /ADDTIONAL_SWAP_FILE
        free # should be 8G+8G=16GB swap
        df /
    - name: Build
      run: |
        export PATH="$PATH:$JAVA_HOME/bin"
        curl -Lo dist.zip https://api.cirrus-ci.com/v1/artifact/github/The-Unstable-World/minecraft_The-Unstable-World/build/jar.zip && 7z x dist.zip
        ./task.nativeimage.sh
